### PR TITLE
Update informations for feet for TALOS + python format

### PR DESCRIPTION
**Pull request by olivier-stasse**
[format] Makes flake8 happy.
Uses Parameter server to set:
 * Remapping of end effector bodies to canonical names: l_ankle, r_ankle, r_wrist, l_wrist to be used by sot-pattern-generator
 * Specify additional information of feet size on the ground.

### CODE REVIEW

**Comment by nim65s** [comment]
@olivier-stasse : should this be included in the release with https://github.com/stack-of-tasks/sot-core/pull/156 ?

**Comment by nim65s** [comment]
And I don't see how this PR "Allows to compile the package without ROS."

**Comment by olivier-stasse** [comment]
> @olivier-stasse : should this be included in the release with [stack-of-tasks/sot-core#156](https://github.com/stack-of-tasks/sot-core/pull/156) ?

Yes please.

**Comment by olivier-stasse** [comment]
> And I don't see how this PR "Allows to compile the package without ROS."

Thanks for pointing this out. I fixed the comments.

**Pull request merged**
