### PR TITLE
Use talos_reduced_v2.urdf.

### PR DESCRIPTION
**Pull request by jmirabel**
The COM between v1 and v2 in the initial config is shifted of 1.5cm along z...

### CODE REVIEW

**Comment by gabrielebndn** [comment]
I think we should discuss about this and possibly talk to PAL about this. The changes in the dynamic are surprising and we should understand them

**Comment by gabrielebndn** [comment]
After discussing at the HPP meeting, I believe this change to be correct for our purposes. It should be merged and released as soon as possible. In the future, we might think of some way for making the system more flexible

**Comment by olivier-stasse** [comment]
Could you be more specific wrt to flexibility. If this is about the robot model, we can probably read the model from the parameter server. This would make sure that we always something consistant.

**Comment by gabrielebndn** [comment]
> Could you be more specific wrt to flexibility. If this is about the robot model, we can probably read the model from the parameter server. This would make sure that we always something consistant.

By flexibility, I mean a system that does not force to update the package to change the exact model being loaded. For instance, by passing a parameter to roscontrol. This is just a suggestion

**Pull request merged**
